# Generated by Django 5.1.2 on 2024-11-05 03:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies_and_user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="category",
            field=models.CharField(
                choices=[
                    ("action", "Action"),
                    ("drama", "Drama"),
                    ("comedy", "Comedy"),
                    ("thriller", "Thriller"),
                    ("horror", "Horror"),
                    ("sci-fi", "Sci-Fi"),
                    ("romance", "Romance"),
                    ("documentary", "Documentary"),
                    ("animation", "Animation"),
                    ("fantasy", "Fantasy"),
                ],
                help_text="Select the category of the movie",
                max_length=20,
            ),
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="movie_id",
            new_name="movie",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="subscription",
            old_name="package_id",
            new_name="package",
        ),
        migrations.RenameField(
            model_name="subscription",
            old_name="user_id",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="movie",
            name="total_views",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveSmallIntegerField(
                help_text="Rate between 1 and 5",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
