# Generated by Django 5.1.2 on 2024-11-06 04:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies_and_user", "0003_alter_movie_title_alter_payment_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="description",
            field=models.TextField(
                default="No description available", help_text="Description about movies"
            ),
        ),
    ]
