# Generated by Django 5.1.2 on 2024-11-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies_and_user", "0004_movie_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="content_access_level",
            field=models.CharField(
                choices=[
                    ("limited", "Limited Content"),
                    ("standard", "Standard Content"),
                    ("full", "Full Content Library"),
                ],
                default="standard",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="device_limit",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Maximum number of devices that can be used simultaneously",
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="duration_in_days",
            field=models.PositiveIntegerField(
                default=30, help_text="Duration of the subscription in days"
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="is_trial",
            field=models.BooleanField(
                default=False, help_text="Indicates if the package is a trial"
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="parental_controls",
            field=models.BooleanField(
                default=False, help_text="Includes parental control features"
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="streaming_quality",
            field=models.CharField(
                choices=[
                    ("SD", "Standard Definition"),
                    ("HD", "High Definition"),
                    ("UHD", "Ultra High Definition/4K"),
                ],
                default="SD",
                max_length=50,
            ),
        ),
    ]
