# Generated by Django 5.1.2 on 2024-11-13 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "movies_and_user",
            "0005_package_content_access_level_package_device_limit_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="movie",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="esewa_order_id",
        ),
        migrations.AddField(
            model_name="payment",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="movies_and_user.subscription",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="auto_renew",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscription",
            name="order_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("expired", "Expired"),
                    ("cancelled", "Cancelled"),
                ],
                default="active",
                max_length=50,
            ),
        ),
    ]
